### ISSUE TITLE
[Note] Core contributors needed

### ISSUE THREAD

**Issue by matthew-dean** [less/less.js#4288]
Sorry that my time has been fairly limited in the last year to contribute & maintain Less. I'm hoping to be able to squeeze some more time for open source projects in the coming months. In the meantime, here's how others can help.

## Core contributions

This repo needs core contributors. Ideally, you should have either a) a record of other open source contributions, and/or b) merged pulls to this repo. A core contributor would help with a) repo maintenance, b) triaging issues, and c) package publishing.

## Tasks

Here are some general top-of-mind maintenance tasks.

- [x] https://github.com/less/less-meta/issues/40
- [ ] https://github.com/less/less-meta/issues/38
- [ ] https://github.com/less/less-meta/issues/41
- [ ] https://github.com/less/less-meta/issues/42
- [ ] https://github.com/less/less-meta/issues/43
- [ ] https://github.com/less/less-meta/issues/44
- [ ] https://github.com/less/less-meta/issues/45
- [ ] https://github.com/less/less-meta/issues/46

I may add more as I think of it.

**Comment by puckowski** [comment]
I have a goal of contributing more to open source projects, so I would be happy to spend more time contributing to Less.js. 

I can help triage issues and I'd like to submit more PRs to resolve bugs and to resolve feature requests. I already subscribe to this repository so I will keep an eye on newly submitted issues and poke through the backlog.

I'll tackle some of the meta items noted above on weekends.

**Comment by puckowski** [comment]
@matthew-dean 

I downloaded Less.js ```4.2.1``` from npm into a new project today to confirm there are no glaring issues. I am able to use ```lessc``` and the browser bundle to compile syntax, including syntax fixed via https://github.com/less/less.js/pull/4237 with Less.js ```4.2.1```.

**Comment by cadomac** [comment]
I've mostly worked on my own projects, but I've made a PR contribution here and there to open source. How stringent is the criteria? I'd love to help out, and I have some experience with managing and maintaining monorepos as well as large refactors. Plus I'm looking for more opportunities to contribute to open source in general.

**Comment by Konarksharma13** [comment]
Hi @matthew-dean. 

I'm interested in contributing to this OSS and would love to become a consistent contributor over time. I have experience with JavaScript and React, and I'm currently improving my TypeScript skills through open source.

Could you suggest the best place to start? Are there any areas, issues, or ongoing efforts where new contributors can make meaningful contributions? I'd also appreciate any advice on what you typically look for in contributors who eventually become core contributors.

Looking forward to contributing and learning from the community. Thanks!
